김승제 과제 검사
BangDori/FE-JavaScript-Study pull request #9
Opened 2023-06-30 15:50 UTC by whitecity01

열심히 했습니다.

2023-06-30 17:45 UTC, BangDori requested changes
전체적으로 네이밍에 조금 더 신경 써 주고, 나머지 부분은 코드 리뷰 확인 후 수정 바랍니다.

2023-06-30 17:45 UTC, BangDori commented on week 7/sj/js/app.js
1. TD가 TodoList를 나타내는 객체라면, TD 보다 더 좋은 네이밍으로 변경하는 것이 좋을 것 같습니다.
2. TD 객체 내부에서 남은 할 일 계산 `hall`과 초기화 함수 `init`를 선언하는 것 보다는 TodoList, 남은 할 일 계산, 초기화 함수를 분리하여 각각 자신의 역할 1가지만 수행할 수 있도록 수정해주는 것이 좋을 것 같습니다.
3. TD 객체의 경우 todoList의 정보를 가지고 있기 때문에, 그와 관련된 기능을 수행하는 todo.js 파일에 속해있는 것이 가독성 향상에 도움이 될 것 같습니다.

2023-06-30 17:45 UTC, BangDori commented on week 7/sj/js/event.js
> +
event.js 코드 리뷰 1번 참고

2023-06-30 17:45 UTC, BangDori commented on week 7/sj/js/event.js
> +    for (let i = 0; i < TD.length; i++) {
event.js 코드 리뷰 2번 참고

2023-06-30 17:45 UTC, BangDori commented on week 7/sj/js/event.js
> +    for (let i = 0; i < TD.length; i++) {
event.js 코드 리뷰 2번 참고

2023-06-30 17:45 UTC, BangDori commented on week 7/sj/js/event.js
> +    TD.done[length] = TD.done[length] == true ? false : true; //done 값 토글
event.js 코드 리뷰 3, 4번 참고

2023-06-30 17:45 UTC, BangDori commented on week 7/sj/js/event.js
> +    for(let i = Number(length)+1 ; i<TD.length; i++){
event.js 코드 리뷰 2번 참고

2023-06-30 17:45 UTC, BangDori commented on week 7/sj/js/event.js
1. 12~18행 `addEventListener`의 경우 이벤트와 콜백함수를 파라미터를 받는데, 콜백함수를 호출할 때 파라미터를 전달 하지 않고 동작할 수 있도록 생각해보는 것이 좋을 것 같습니다.
2. 자바스크립트에서는 배열을 순회할 때 `for`문을 사용하기보다, `forEach`, `map`, `filter `등의 내장 함수를 사용하는 것을 권장하고 있습니다. 위 코드에서 `for`문을 사용하기 보다, 가독성이 높은 `forEach`를 사용하는 방법에 대해 고려해 보는 것이 좋을 것 같습니다.
3. 삼항 연산자를 사용할 때,  TD.done[length] == true 말고 다른 방법이 있을지 생각해봅시다.
4. 기존의 C, C++, Java 등의 언어들과 달리 자바스크립트에서는 비교 연산자로 ===, !== 3가지를 사용합니다. 그 이유는, 자바스크립트에서는 타입을 지정해주지 않기 때문입니다. 스스로 공부하고 수정해봅시다.

2023-06-30 17:45 UTC, BangDori commented on week 7/sj/js/todo.js
Todo의 word 수정이 정상적으로 이루어지지 않습니다.

2023-07-03 16:13 UTC, mingking2 requested changes
바꿔주세요

2023-07-03 16:13 UTC, mingking2 commented on week 7/sj/js/event.js
> +}
CRUD 기능이 todo.js에 한번에 있는게 좋은거 같아요

2023-07-03 16:13 UTC, mingking2 commented on week 7/sj/js/todo.js
렌더링 관련 부분은 event.js로 옮겨주세요

2023-07-04 02:26 UTC, merged